name: indicut_ai
description: "CapCut India like AI Video and Image Editor"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  http: ^1.2.1
  
